###################################################################################
#        #######      ##     ##       ##########      ##         ########         #
#        ##    ##     ##     ##           ##          ##         ##     ##        #
#        ##   ##      ##     ##           ##          ##         ##      ##       #
#        ## ##        ##     ##           ##          ##         ##       ##      #
#        ##   ##      ##     ##           ##          ##         ##      ##       #
#        ##    ##     ##     ##           ##          ##         ##     ##        #
#        #######      #########       ##########      #######    #########        #
###################################################################################        
name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Build and Push Docker Image
        env:
          IMAGE_TAG: 5.1.0
          ECR_REPOSITORY: mdaca/jupyter/jupyter-docker-stacks-foundation
        run: |
          # Build Docker Image
          docker buildx build --tag $ECR_REPOSITORY:$IMAGE_TAG .

          # Authenticate Docker with ECR
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPOSITORY

          # Push Docker Image to ECR
          docker push $ECR_REPOSITORY:$IMAGE_TAG
