name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push docker-stacks-foundation Docker Image
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          ECR_REPOSITORY: mdaca/jupyter/jupyter-docker-stacks-foundation
        run: |
          # Set ENV for AW Cred
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set default.region $AWS_REGION
          # Get token from ECR and Docker login
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$AWS_REGION.amazonaws.com
          IMAGE_TAG=5.1.0
          # Set ENV for Docker build
          ECR_REPOSITORY=mdaca/jupyter/jupyter-docker-stacks-foundation
          REPOSITORY=$ECR_REPOSITORY
          REGISTRY=201959883603.dkr.ecr.us-east-2.amazonaws.com
          # Build the Docker image
          docker build -f images/docker-stacks-foundation/Dockerfile -t $REGISTRY/$REPOSITORY:$IMAGE_TAG images/docker-stacks-foundation

          # Push the Docker image
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

          # Add latest tag
          docker tag $REGISTRY/$REPOSITORY:$IMAGE_TAG $REGISTRY/$REPOSITORY:latest

          # push latest Docker Image
          docker push $REGISTRY/$REPOSITORY:latest

      - name: Build and Push Jupyter-base-notebook Docker Image
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-2
          IMAGE_TAG: 5.1.0
          ECR_REPOSITORY: mdaca/jupyter/jupyter-base-notebook
        run: |
          # Set ENV for AW Cred
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set default.region $AWS_REGION

          # Get token from ECR and Docker login
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$AWS_REGION.amazonaws.com
          IMAGE_TAG=5.1.0
 
          # Set ENV for Docker build
          ECR_REPOSITORY=mdaca/jupyter/jupyter-base-notebook
          REPOSITORY=$ECR_REPOSITORY
          REGISTRY=201959883603.dkr.ecr.us-east-2.amazonaws.com

          # Build the Docker image
          docker build -f images/base-notebook/Dockerfile -t $REGISTRY/$REPOSITORY:$IMAGE_TAG images/base-notebook

          # Push the Docker image
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

          # Add latest tag
          docker tag $REGISTRY/$REPOSITORY:$IMAGE_TAG $REGISTRY/$REPOSITORY:latest

          # push latest Docker Image
          docker push $REGISTRY/$REPOSITORY:latest

      - name: Build and Push Jupyter-minimal-notebook Docker Image
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-2
          IMAGE_TAG: 5.1.0
          ECR_REPOSITORY: mdaca/jupyter/jupyter-minimal-notebook
        run: |
          # Set ENV for AW Cred
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set default.region $AWS_REGION
 
          # Get token from ECR and Docker login
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$AWS_REGION.amazonaws.com
          IMAGE_TAG=5.1.0
 
          # Set ENV for Docker build
          ECR_REPOSITORY=mdaca/jupyter/jupyter-minimal-notebook
          REPOSITORY=$ECR_REPOSITORY
          REGISTRY=201959883603.dkr.ecr.us-east-2.amazonaws.com

         # Build the Docker image
          docker build -f images/minimal-notebook/Dockerfile -t $REGISTRY/$REPOSITORY:$IMAGE_TAG images/minimal-notebook

          # Push the Docker image
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

          # Add latest tag
          docker tag $REGISTRY/$REPOSITORY:$IMAGE_TAG $REGISTRY/$REPOSITORY:latest

          # push latest Docker Image
          docker push $REGISTRY/$REPOSITORY:latest
